apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.name" . }}
  labels:
{{ include "mychart.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mychart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mychart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          lifecycle:
              preStop:
                exec:
                  command: ["/bin/sh", "-c", "sh script/pre_stop.sh"]
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: [ "/bin/sh", "-c", "sh  script/start.sh" ]
          ports:
            - name: grpc
              containerPort: 10000
          volumeMounts:
            - name: config-volume
              mountPath: "/etc/config"
            - name: go-logs
              mountPath: "/tmp"
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      imagePullSecrets:
        - name: regcred

      volumes:
        - name: config-volume
          configMap:
            name: micro-config 
            items:
                - key: config.toml
                  path: config.toml
        - name: go-logs
          hostPath:
            path: "{{ .Values.logpath }}"
      restartPolicy: Always 
