// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order/order.proto

package order

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// OrderCreateRequest
type OrderCreateRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ProductID            []string `protobuf:"bytes,2,rep,name=productID,proto3" json:"productID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderCreateRequest) Reset()         { *m = OrderCreateRequest{} }
func (m *OrderCreateRequest) String() string { return proto.CompactTextString(m) }
func (*OrderCreateRequest) ProtoMessage()    {}
func (*OrderCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{0}
}

func (m *OrderCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCreateRequest.Unmarshal(m, b)
}
func (m *OrderCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCreateRequest.Marshal(b, m, deterministic)
}
func (m *OrderCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCreateRequest.Merge(m, src)
}
func (m *OrderCreateRequest) XXX_Size() int {
	return xxx_messageInfo_OrderCreateRequest.Size(m)
}
func (m *OrderCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCreateRequest proto.InternalMessageInfo

func (m *OrderCreateRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *OrderCreateRequest) GetProductID() []string {
	if m != nil {
		return m.ProductID
	}
	return nil
}

type OrderQueryRequest struct {
	OrderID              string   `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderQueryRequest) Reset()         { *m = OrderQueryRequest{} }
func (m *OrderQueryRequest) String() string { return proto.CompactTextString(m) }
func (*OrderQueryRequest) ProtoMessage()    {}
func (*OrderQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{1}
}

func (m *OrderQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderQueryRequest.Unmarshal(m, b)
}
func (m *OrderQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderQueryRequest.Marshal(b, m, deterministic)
}
func (m *OrderQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderQueryRequest.Merge(m, src)
}
func (m *OrderQueryRequest) XXX_Size() int {
	return xxx_messageInfo_OrderQueryRequest.Size(m)
}
func (m *OrderQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderQueryRequest proto.InternalMessageInfo

func (m *OrderQueryRequest) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

// OrderResponse
type OrderResponse struct {
	OrderMsg             *OrderMsg `protobuf:"bytes,1,opt,name=orderMsg,proto3" json:"orderMsg,omitempty"`
	Result               *Result   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Balance              string    `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *OrderResponse) Reset()         { *m = OrderResponse{} }
func (m *OrderResponse) String() string { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()    {}
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{2}
}

func (m *OrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResponse.Unmarshal(m, b)
}
func (m *OrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResponse.Marshal(b, m, deterministic)
}
func (m *OrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResponse.Merge(m, src)
}
func (m *OrderResponse) XXX_Size() int {
	return xxx_messageInfo_OrderResponse.Size(m)
}
func (m *OrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResponse proto.InternalMessageInfo

func (m *OrderResponse) GetOrderMsg() *OrderMsg {
	if m != nil {
		return m.OrderMsg
	}
	return nil
}

func (m *OrderResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *OrderResponse) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

type OrderMsg struct {
	OrderID              string   `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	CreateTime           string   `protobuf:"bytes,2,opt,name=createTime,proto3" json:"createTime,omitempty"`
	TotolMoney           string   `protobuf:"bytes,3,opt,name=totolMoney,proto3" json:"totolMoney,omitempty"`
	ProductID            []string `protobuf:"bytes,4,rep,name=productID,proto3" json:"productID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderMsg) Reset()         { *m = OrderMsg{} }
func (m *OrderMsg) String() string { return proto.CompactTextString(m) }
func (*OrderMsg) ProtoMessage()    {}
func (*OrderMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{3}
}

func (m *OrderMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderMsg.Unmarshal(m, b)
}
func (m *OrderMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderMsg.Marshal(b, m, deterministic)
}
func (m *OrderMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderMsg.Merge(m, src)
}
func (m *OrderMsg) XXX_Size() int {
	return xxx_messageInfo_OrderMsg.Size(m)
}
func (m *OrderMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderMsg.DiscardUnknown(m)
}

var xxx_messageInfo_OrderMsg proto.InternalMessageInfo

func (m *OrderMsg) GetOrderID() string {
	if m != nil {
		return m.OrderID
	}
	return ""
}

func (m *OrderMsg) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *OrderMsg) GetTotolMoney() string {
	if m != nil {
		return m.TotolMoney
	}
	return ""
}

func (m *OrderMsg) GetProductID() []string {
	if m != nil {
		return m.ProductID
	}
	return nil
}

// 返回码与返回状态
type Result struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa47a2077d8980ed, []int{4}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*OrderCreateRequest)(nil), "order.OrderCreateRequest")
	proto.RegisterType((*OrderQueryRequest)(nil), "order.OrderQueryRequest")
	proto.RegisterType((*OrderResponse)(nil), "order.OrderResponse")
	proto.RegisterType((*OrderMsg)(nil), "order.OrderMsg")
	proto.RegisterType((*Result)(nil), "order.Result")
}

func init() { proto.RegisterFile("order/order.proto", fileDescriptor_fa47a2077d8980ed) }

var fileDescriptor_fa47a2077d8980ed = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0xfd, 0xd2, 0xb4, 0xf9, 0x9a, 0x29, 0x45, 0x3b, 0x88, 0xac, 0x22, 0x52, 0x02, 0x42, 0x41,
	0xac, 0x50, 0xef, 0x22, 0xd8, 0x4b, 0x85, 0x52, 0x5c, 0xfc, 0x03, 0x6d, 0x3a, 0x14, 0xa1, 0xed,
	0xc6, 0xdd, 0xcd, 0xa1, 0x07, 0x2f, 0xde, 0xfc, 0xd7, 0x92, 0xd9, 0x4d, 0xdd, 0x0a, 0xbd, 0x84,
	0x99, 0x37, 0x2f, 0xef, 0x0d, 0x6f, 0x16, 0x7a, 0x4a, 0x2f, 0x49, 0xdf, 0xf3, 0x77, 0x58, 0x68,
	0x65, 0x15, 0xb6, 0xb8, 0xc9, 0x5e, 0x00, 0x67, 0x55, 0xf1, 0xac, 0x69, 0x6e, 0x49, 0xd2, 0x47,
	0x49, 0xc6, 0xe2, 0x39, 0x24, 0xa5, 0x21, 0x3d, 0x19, 0x8b, 0xa8, 0x1f, 0x0d, 0x52, 0xe9, 0x3b,
	0xbc, 0x82, 0xb4, 0xd0, 0x6a, 0x59, 0xe6, 0x76, 0x32, 0x16, 0x8d, 0x7e, 0x3c, 0x48, 0xe5, 0x2f,
	0x90, 0xdd, 0x41, 0x8f, 0xb5, 0x5e, 0x4b, 0xd2, 0xbb, 0x5a, 0x4a, 0xc0, 0x7f, 0x76, 0xda, 0x6b,
	0xd5, 0x6d, 0xf6, 0x09, 0x5d, 0xa6, 0x4b, 0x32, 0x85, 0xda, 0x1a, 0xc2, 0x5b, 0x68, 0xf3, 0x6c,
	0x6a, 0x56, 0xcc, 0xed, 0x8c, 0x4e, 0x86, 0x6e, 0xe5, 0x99, 0x87, 0xe5, 0x9e, 0x80, 0x37, 0x90,
	0x68, 0x32, 0xe5, 0xda, 0x8a, 0x06, 0x53, 0xbb, 0x9e, 0x2a, 0x19, 0x94, 0x7e, 0x58, 0xd9, 0x2f,
	0xe6, 0xeb, 0xf9, 0x36, 0x27, 0x11, 0x3b, 0x7b, 0xdf, 0x66, 0x5f, 0x11, 0xb4, 0x6b, 0xdd, 0xe3,
	0x5b, 0xe2, 0x35, 0x40, 0xce, 0xd9, 0xbc, 0xbd, 0x6f, 0x88, 0xbd, 0x52, 0x19, 0x20, 0xd5, 0xdc,
	0x2a, 0xab, 0xd6, 0x53, 0xb5, 0xa5, 0x9d, 0xf7, 0x08, 0x90, 0xc3, 0xc8, 0x9a, 0x7f, 0x23, 0x1b,
	0x42, 0xe2, 0x16, 0x46, 0x84, 0x66, 0xae, 0x96, 0xc4, 0xf6, 0xb1, 0xe4, 0x1a, 0x4f, 0x21, 0xde,
	0x98, 0x95, 0x37, 0xad, 0xca, 0xd1, 0x77, 0x04, 0x2d, 0x5e, 0x1a, 0x9f, 0xa0, 0xe3, 0x6e, 0xe6,
	0xda, 0x8b, 0x30, 0xa9, 0x83, 0x63, 0x5e, 0x9e, 0x85, 0xa3, 0x3a, 0xec, 0xec, 0x1f, 0x3e, 0x02,
	0xf0, 0xa5, 0x9c, 0x80, 0x08, 0x59, 0xe1, 0x05, 0x8f, 0xfd, 0xbf, 0x48, 0xf8, 0x21, 0x3d, 0xfc,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xdc, 0xdf, 0x61, 0x80, 0x5d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderClient interface {
	// order create
	CreateOrder(ctx context.Context, in *OrderCreateRequest, opts ...grpc.CallOption) (*OrderResponse, error)
	// order query
	QueryOrder(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*OrderResponse, error)
}

type orderClient struct {
	cc *grpc.ClientConn
}

func NewOrderClient(cc *grpc.ClientConn) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) CreateOrder(ctx context.Context, in *OrderCreateRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, "/order.Order/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) QueryOrder(ctx context.Context, in *OrderQueryRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, "/order.Order/QueryOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
type OrderServer interface {
	// order create
	CreateOrder(context.Context, *OrderCreateRequest) (*OrderResponse, error)
	// order query
	QueryOrder(context.Context, *OrderQueryRequest) (*OrderResponse, error)
}

// UnimplementedOrderServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServer struct {
}

func (*UnimplementedOrderServer) CreateOrder(ctx context.Context, req *OrderCreateRequest) (*OrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (*UnimplementedOrderServer) QueryOrder(ctx context.Context, req *OrderQueryRequest) (*OrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryOrder not implemented")
}

func RegisterOrderServer(s *grpc.Server, srv OrderServer) {
	s.RegisterService(&_Order_serviceDesc, srv)
}

func _Order_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateOrder(ctx, req.(*OrderCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_QueryOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).QueryOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.Order/QueryOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).QueryOrder(ctx, req.(*OrderQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Order_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _Order_CreateOrder_Handler,
		},
		{
			MethodName: "QueryOrder",
			Handler:    _Order_QueryOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order/order.proto",
}
