# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gongfupanda2/micro-framework
  tag: latest
  imagePullPolicy: Never

logpath: /tmp/log/

service:
  type: NodePort
  nodePort: 30000

ingress:
  tls: 
    - secretName: tls-secret
      hosts:
        - micro-framework.mydomain.com

