apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/grpc-backend: "true"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    name: micro-framework

spec:
    rules:
    - host: micro-framework.mydomain.com
      http:
        paths: 
        - backend:
            serviceName: micro-framework
            servicePort: grpc
